BokningsSystem_SlutUppgift/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BokningsSystem_SlutUppgift.Helpers;
using BokningsSystem_SlutUppgift.Models;
using BokningsSystem_SlutUppgift.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BokningsSystem_SlutUppgift.Controllers
{
    public class BookingsController : Controller
    {
        private bool ValidateBooking(Booking booking)
        {
            bool isValid = true;

            //Check if From date is after To date
            if (booking.From > booking.To)
            {
                ModelState.AddModelError("Booking.From", "Start date cannot be after end date");
                 var CreateBookingViewModel = new CreateBookingViewModel() { Giraffes = DbContext.Giraffes, Booking = booking };
                isValid = false;
            }
            //1. Fetch all bookings with the same GiraffeID as the new one

            List<Booking> oldBookings = DbContext.Bookings.Where(b => b.GiraffeId == booking.GiraffeId).ToList();

            //2. Check if any of the dates in the bookings overlap
            foreach (var oldBooking in oldBookings)
            {
                if (DateHelpers.HasSharedDateInterval(booking.From, booking.To, oldBooking.From, oldBooking.To))
                {
                    ModelState.AddModelError("Booking.From", "Date already occupied.");
                    var createBookingViewModel = new CreateBookingViewModel() { Giraffes = DbContext.Giraffes, Booking = booking };
                    isValid = false;
                }
            }
            return isValid;
        }

        public void TotalCostCounter(Booking booking, Giraffe giraffe)
        {

            var timeBooked = booking.To.Subtract(booking.From).TotalHours;

            var costBooked = (timeBooked * giraffe.Price);

            var costBookedInt = Convert.ToInt32(costBooked);

            booking.TotalCost = costBookedInt;
        }
       
        public IActionResult Index()
        {
            var bookings = DbContext.Bookings;

            return View(bookings);
        }

        public IActionResult Create()
        {
            var CreateBookingViewModel = new CreateBookingViewModel() { Giraffes = DbContext.Giraffes };
            return View(CreateBookingViewModel);
        }

        [HttpPost]

        public IActionResult Create(Booking booking)
        {
            //if (!ValidateBooking(booking))
            //{
            //    var CreateBookingViewModel = new CreateBookingViewModel() { Giraffes = DbContext.Giraffes, Booking = booking };
            //    return View(CreateBookingViewModel);
            //}

            //hämta valda giraffens properties
            var giraffe = DbContext.Giraffes.FirstOrDefault(g => g.Id == booking.GiraffeId);

            if (giraffe == null)
            {
                return RedirectToAction(nameof(Create));
            }

            //räkna ut total kostnad för bokning

            TotalCostCounter(booking, giraffe);

            booking.Id = Guid.NewGuid();
            booking.GiraffeName = giraffe.Name;
            booking.BookerEmail = booking.BookerEmail;

            DbContext.Bookings.Add(booking);

            return Redirect("https://localhost:44338/Bookings");
        }

        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = DbContext.Bookings.SingleOrDefault(b => b.Id == id);


            if (booking == null)
            {
                return NotFound();
            }

            var editBookingViewModel = new EditBookingViewModel() { Booking = booking,  Giraffes = DbContext.Giraffes };
           
            return View(editBookingViewModel);
        }

        [HttpPost]
        public IActionResult Edit(Booking booking)
        {

            if (ModelState.IsValid)
            {
                booking.GiraffeName = DbContext.Giraffes.SingleOrDefault(g => g.Id == booking.GiraffeId).Name;

                var giraffe = DbContext.Giraffes.FirstOrDefault(g => g.Id == booking.GiraffeId);

                TotalCostCounter(booking, giraffe);

                var bookingIndex = DbContext.Bookings.FindIndex(b => b.Id == booking.Id);

                if (bookingIndex == -1)
                {
                    return NotFound();
                }

                DbContext.Bookings[bookingIndex] = booking;
                
                return RedirectToAction(nameof(Index));
            }

            return View(booking);
        }


        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giraffe = DbContext.Bookings.FirstOrDefault(b => b.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);

        }

        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var giraffe = DbContext.Bookings.FirstOrDefault(b => b.Id == id);

            if(giraffe == null)
            {
                return NotFound();
            }

            DbContext.Bookings.Remove(giraffe);

            return RedirectToAction("Index");
        }

    }
}

BokningsSystem_SlutUppgift/Controllers/GiraffesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BokningsSystem_SlutUppgift.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BokningsSystem_SlutUppgift.Controllers
{
    public class GiraffesController : Controller
    {
        public IActionResult Index()
        {

            var giraffes = DbContext.Giraffes;

            return View(giraffes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(Giraffe giraffe)
        {
            giraffe.Id = Guid.NewGuid();
            giraffe.Name = giraffe.Name;
            giraffe.PicId = giraffe.PicId;
            DbContext.Giraffes.Add(giraffe);

            return Redirect("https://localhost:44338/Giraffes");

        }

        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giraffe = DbContext.Giraffes.SingleOrDefault(g => g.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);
        }

        [HttpPost]
        public IActionResult Edit(Giraffe giraffe)
        {
            if (ModelState.IsValid)
            {
                var giraffeIndex = DbContext.Giraffes.FindIndex(g => g.Id == giraffe.Id);

                if (giraffeIndex == -1)
                {
                    return NotFound();
                }

                DbContext.Giraffes[giraffeIndex] = giraffe;

                return RedirectToAction(nameof(Index));
            }
            return View(giraffe);
        }

        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giraffe = DbContext.Giraffes.FirstOrDefault(g => g.Id == id);

            if(giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);
        }

        [HttpPost]
        public IActionResult Delete(Giraffe giraffe)
        {
            var giraffeToDelete = DbContext.Giraffes.FirstOrDefault(g => g.Id == giraffe.Id);

            if (giraffeToDelete == null)
            {
                return NotFound();
            }

            DbContext.Giraffes.Remove(giraffeToDelete);

            return RedirectToAction("Index");
        }

        
    }

}

BokningsSystem_SlutUppgift/Controllers/TermsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BokningsSystem_SlutUppgift.Controllers
{
    public class TermsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BokningsSystem_SlutUppgift/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Giraffe Booker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="HeaderAndFooterStyle">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Giraffe Booker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark navBar" asp-area="" asp-controller="Giraffes" asp-action="Index">Giraffes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark navBar" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                        <li class="nav-item">
                                 <a class="nav-link text-dark navBar" asp-area="" asp-controller="Terms" asp-action="Index">Terms of service</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted, HeaderAndFooterStyle">
        <div class="container">
            &copy; 2020 - GiraffeBookingCorp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>